language: java
sudo: false
install: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - pwd
  - cd NetMusicPlayer
install:
  - mvn clean install -DskipTests
addons:
  sonarcloud:
    organization: "rsl1122-github"
    token:
      secure: "GZIp+s6gHPEXw4jbJvxwNN7yxtC56aJziJezimuoHbVseopfhGeMlRfUeoFPUOxecfUqFXpcaD9R8blheakd1MPMhiZ0E7FxuFiqHVakTnB7LpG1jZpyihw5pWzCywk8+maRdR2o3Vdj6+21kL4/uNkANvC5YOVGGJ1gifKn67KmMylTMSk7w5hoDNnegxXnTt1sCZ3Z81dsGlc3oML+1uZwN2eTulVd4vEKX4F5R/SSIflQIsB9CFcFZPQpUa/qL9fj0BBDFUHhWbwBocrfa/S4ycdiq+kjN15gjzzk7GG5jiR4pLjtuUubT9sjrBnW8l+reuZh6aFXSGeIEI3083BBeNIEWoiUDBzq7U9+MKTmqLI0oeUgcDRGSyrS0tSg5e7XN6h69IMJf9Qjykds3fOU2HFSwRZ0rIOySaCbzLnmoaAyFKC0z/r/2FdlsUiE/SL1YrSBREZq1HCfY/ZZAj4Re/crf8lxUHIH2SmcxWk2VO6tw9X+T7pH58uq7oN3pKCijM/HS3nO4Ks07e8n6LLO+S1WCB0nMZy1BFXL6Eqh4nqYpEzaFgECxSOeMdAfeFGqVo3IYr8i1RjXT0eS8gOLEu2VwCr1PVuEMHMr+0ffE17CSWTtza5dnOHjOWlKJ2GUvTxzFT9fqgVVfi9oYJ9LBcCsJcm0QGb5rHEKQ3w="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
